### ISSUE TITLE
Multi-file import error

### ISSUE THREAD

**Issue by Thrysis** [pycroscopy/sidpy#169]
Hi! I have been trying to use this to import some ibw files, and have had good success for one file at a time, but as soon as I try to import more than one file using the multiple_files=True optional addition to open_file_dialogQT(), I get an error that the tuple object is not callable.

Output log and useful:
OS: Windows 11 Pro v 10.0.22621
PC: Lenovo Thinkpad X1 Yoga Gen 6
Python 3.8, Spyder 4.2.5
SciFiReaders version:  0.0.6
sidpy version:  0.11.1
Traceback (most recent call last):

  File "C:\Users\mattc\OneDrive\Documents\Casimir\cylinder_fitting\cylFit\ibwReading.ipy", line 17, in <module>
    file_names = sidpy.io.interface_utils.openfile_dialog_QT(multiple_files=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sidpy\io\interface_utils.py", line 256, in openfile_dialog_QT
    fnames, file_filter = func(parent, caption, file_path, filter=file_types, options=[QtCore.Qt.WindowStaysOnTopHint])

  TypeError: 'tuple' object is not callable

I have fed it a few basic topography images (.ibw files) that worked when selecting a single file.

**Comment by ramav87** [comment]
Interesting! This feature is not actually tested for all of our readers. @gduscher is there something about the EM readers that enables this, that the others don't?
